
files:
  /etc/conduktor/config.yaml:
    mode: 644
    content: |
      ---
      # Conduktor configuration can interpolate env vars values natively.
      organization:
        name: ${ORG_NAME}

      clusters:
        - id: confluent-pkc
          name: Confluent
          color: "#E70000"
          ignoreUntrustedCertificate: false
          bootstrapServers: ${PROD_BOOTSTRAP_SERVERS}
          properties: |
            client.id=conduktor
            default.api.timeout.ms=5000
            request.timeout.ms=5000
            security.protocol=SASL_SSL
            sasl.mechanism=PLAIN
            sasl.jaas.config=${PROD_SASL_JAAS_CONFIG}
          schemaRegistry:
            id: confluent-sr
            url: ${PROD_SCHEMA_REGISTRY_URL}
            ignoreUntrustedCertificate: false
            security:
              username: ${PROD_SCHEMA_REGISTRY_USERNAME}
              password: ${PROD_SCHEMA_REGISTRY_PASSWORD}
          labels: {}

      license: ${LICENSE_KEY}
      auth:
        demo-users:
          - email: ${ADMIN_EMAIL}
            password: ${ADMIN_PSW}
            groups:
              - ADMIN


  /etc/nginx/conf.d/001.conf:
    # Configuration file for NGINX to add SSL termination
    mode: 644
    context: jinja2
    content: |
      upstream conduktor {
          server 127.0.0.1:80;
          keepalive 64;
      }
      server {
          listen 8080;
          server_name _;
          location / {
              stub_status;
              access_log   off;
          }
      }
      server {
          listen 443 ssl;
          server_name ${{ env_var('SERVER_NAME') | safe }};

          ssl_certificate /etc/nginx/ssl/nginx.crt;
          ssl_certificate_key /etc/nginx/ssl/nginx.key;
          ssl_protocols TLSv1.3 TLSv1.2;
          ssl_prefer_server_ciphers on;
          ssl_ecdh_curve secp521r1:secp384r1;
          ssl_ciphers EECDH+AESGCM:EECDH+AES256;
          ssl_session_cache shared:TLS:2m;
          ssl_buffer_size 4k;

          location ~ /ws/graphql {
            proxy_pass http://conduktor;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
          }
          location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $host;
            proxy_pass http://conduktor;
          }
      }

certificates:
  x509:
    /etc/nginx/ssl:
      keyFileName: nginx.key
      certFileName: nginx.crt
